/**
 * MCP server for the SOC IoC corpus, served from Cloudflare Workers over D1.
 *
 * The daily job pushes confirmed indicators here; this Worker only reads them.
 * It never scrapes, never writes, and never returns article bodies - those stay
 * in the audit JSON, because they are 26 publishers' text and no query needs
 * them.
 */

import pslRules from "./psl.json";
import { assess, renderHeartbeat, taipeiDate, type HeartbeatState } from "./heartbeat";

export interface Env {
  DB: D1Database;
  /** Fallback single token, for a deployment that has not issued any yet. */
  BOOTSTRAP_TOKEN?: string;
  /* Set with `wrangler secret put`. Absent, the heartbeat logs and sends nothing. */
  RESEND_API_KEY?: string;
  RESEND_FROM?: string;
  /** Operational alerts only; never the daily report's recipients. */
  ALERT_TO?: string;
}

// Generated by `npm run psl` from the same list the Python package bundles, so
// the boundary a report was written against matches the one a query uses.
const PSL_NORMAL = new Set(pslRules.normal);
const PSL_WILDCARD = new Set(pslRules.wildcard);
const PSL_EXCEPTION = new Set(pslRules.exception);

const PROTOCOL_VERSION = "2025-06-18";
const MAX_LIMIT = 200;
const DEFAULT_LIMIT = 40;
/** A log can name many hosts; cap the batch so one call cannot scan forever. */
const MAX_BATCH = 100;

type Json = Record<string, unknown>;

interface Caller {
  label: string;
  scopes: Set<string>;
}

/* -------------------------------------------------------------- auth ----- */

async function sha256Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** Constant-time compare, so a wrong token cannot be found byte by byte. */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function authenticate(request: Request, env: Env): Promise<Caller | null> {
  const header = request.headers.get("authorization") ?? "";
  if (!header.startsWith("Bearer ")) return null;
  const presented = header.slice(7).trim();
  if (!presented) return null;

  const hash = await sha256Hex(presented);
  const row = await env.DB.prepare(
    `SELECT label, scopes, expires_at, revoked_at
       FROM tokens WHERE token_sha256 = ?`,
  )
    .bind(hash)
    .first<{ label: string; scopes: string; expires_at: string | null; revoked_at: string | null }>();

  if (row) {
    if (row.revoked_at) return null;
    if (row.expires_at && new Date(row.expires_at) < new Date()) return null;
    // Usage is recorded so an unused or runaway token is visible later.
    await env.DB.prepare(
      `UPDATE tokens SET last_used_at = ?, call_count = call_count + 1
         WHERE token_sha256 = ?`,
    )
      .bind(new Date().toISOString(), hash)
      .run();
    return { label: row.label, scopes: new Set(row.scopes.split(/[,\s]+/).filter(Boolean)) };
  }

  if (env.BOOTSTRAP_TOKEN && timingSafeEqual(presented, env.BOOTSTRAP_TOKEN)) {
    return { label: "bootstrap", scopes: new Set(["read", "context"]) };
  }
  return null;
}

/* ------------------------------------------------------------- shaping --- */

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

function validDate(value: unknown): string | null {
  return typeof value === "string" && DATE_RE.test(value) ? value : null;
}

function clampLimit(value: unknown): number {
  const n = typeof value === "number" ? Math.floor(value) : DEFAULT_LIMIT;
  return Math.min(Math.max(n, 1), MAX_LIMIT);
}

/**
 * The registry-controlled tail of a host, by the publicsuffix.org algorithm:
 * the rule matching the most labels wins, an exception beats a wildcard, and an
 * unlisted TLD falls back to the implicit `*` rule so a novel TLD does not make
 * the whole host look registrable.
 */
function publicSuffix(labels: string[]): string {
  for (let i = 0; i < labels.length; i += 1) {
    const candidate = labels.slice(i).join(".");
    if (PSL_EXCEPTION.has(candidate)) return labels.slice(i + 1).join(".");
    const parent = labels.slice(i + 1).join(".");
    if (parent && PSL_WILDCARD.has(parent)) return candidate;
    if (PSL_NORMAL.has(candidate)) return candidate;
  }
  return labels[labels.length - 1];
}

/**
 * A log names the host that actually resolved, which is often a child of the
 * host the report named, so `a.b.evil.com` has to still find `evil.com`.
 *
 * Parents stop at the registrable domain. Walking all the way down produced
 * `co.uk` and `github.io` as lookup keys, and a report that named either would
 * then match every unrelated tenant beneath it. Nothing at or above the public
 * suffix belongs to anyone in particular, so nothing there is a useful key.
 */
function hostCandidates(value: string): string[] {
  const host = value.trim().toLowerCase().replace(/\.$/, "");
  if (!host.includes(".") || /^[\d.]+$/.test(host)) return [host];
  const labels = host.split(".");
  const suffixLength = publicSuffix(labels).split(".").length;
  const out: string[] = [];
  for (let i = 0; i <= labels.length - suffixLength - 1; i += 1) {
    out.push(labels.slice(i).join("."));
  }
  // The host is itself a public suffix, so it has no registrable parent. Look
  // it up verbatim rather than returning nothing.
  return out.length ? out : [host];
}

function rowToHit(row: Json, caller: Caller): Json {
  const hit: Json = {
    report_date: row.report_date,
    indicator_type: row.indicator_type,
    value: row.value,
    status: row.status,
    action: row.action,
    priority: row.priority,
    reason: row.reason,
    kev: row.kev === null || row.kev === undefined ? null : Boolean(row.kev),
    kev_due_date: row.kev_due_date,
    cvss_score: row.cvss_score,
    cvss_severity: row.cvss_severity,
    source: row.source,
    article_title: row.article_title,
    article_url: row.article_url,
    section: row.section,
    // Names the rule that kept this off the block list, when one did. The
    // reason string beside it is Chinese prose; a consumer deciding whether a
    // hit is a public resolver or a registry boundary should not have to match
    // substrings of it.
    benign_basis: row.benign_basis ?? null,
    epss_score: row.epss_score ?? null,
    epss_percentile: row.epss_percentile ?? null,
  };
  // The context line is a verbatim source sentence. A token without the scope
  // gets the citation and can read it at the publisher.
  if (caller.scopes.has("context")) hit.context = row.context ?? null;
  return hit;
}

/* --------------------------------------------------------------- tools --- */

const TOOLS = [
  {
    name: "list_reports",
    description: "List ingested daily reports, newest first, with their counts.",
    inputSchema: {
      type: "object",
      properties: { limit: { type: "number", description: "max reports (default 40)" } },
    },
  },
  {
    name: "get_report_summary",
    description:
      "One report's subject, window, priority line and patch/block/hunt/KEV counts. Omit date for the newest.",
    inputSchema: {
      type: "object",
      properties: { date: { type: "string", description: "YYYY-MM-DD" } },
    },
  },
  {
    name: "search_confirmed_iocs",
    description:
      "Search confirmed indicators across every ingested day. Filter by text, action (patch/block/hunt), indicator_type, or a single date.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        date: { type: "string", description: "YYYY-MM-DD; omit to search all days" },
        since: { type: "string", description: "YYYY-MM-DD lower bound" },
        action: { type: "string" },
        indicator_type: { type: "string" },
        limit: { type: "number" },
      },
    },
  },
  {
    name: "lookup_ioc",
    description:
      "Look one indicator up across every day. For a hostname it also tries each parent domain, so a log's FQDN still matches a report's apex.",
    inputSchema: {
      type: "object",
      properties: {
        value: { type: "string" },
        since: { type: "string", description: "YYYY-MM-DD lower bound" },
      },
      required: ["value"],
    },
  },
  {
    name: "lookup_iocs",
    description:
      "Look up many indicators at once - the values pulled out of a log - and get every day each one was reported. Up to 100 per call.",
    inputSchema: {
      type: "object",
      properties: {
        values: { type: "array", items: { type: "string" } },
        since: { type: "string", description: "YYYY-MM-DD lower bound" },
      },
      required: ["values"],
    },
  },
] as const;

async function listReports(env: Env, args: Json): Promise<Json> {
  const { results } = await env.DB.prepare(
    `SELECT report_date, subject, article_count, confirmed_ioc_count,
            patch_count, block_count, hunt_count, kev_count, unavailable_count,
            generated_at
       FROM reports ORDER BY report_date DESC LIMIT ?`,
  )
    .bind(clampLimit(args.limit))
    .all<Json>();
  return { count: results.length, reports: results };
}

async function reportSummary(env: Env, args: Json): Promise<Json> {
  const date = validDate(args.date);
  const row = date
    ? await env.DB.prepare(`SELECT * FROM reports WHERE report_date = ?`).bind(date).first<Json>()
    : await env.DB.prepare(`SELECT * FROM reports ORDER BY report_date DESC LIMIT 1`).first<Json>();
  if (!row) return { error: date ? `no report for ${date}` : "no reports ingested yet" };
  let enrichment: unknown = null;
  try {
    enrichment = JSON.parse(String(row.enrichment_json ?? "{}"));
  } catch {
    enrichment = null;
  }
  const { enrichment_json, ...rest } = row;
  return { ...rest, enrichment };
}

async function searchIocs(env: Env, args: Json, caller: Caller): Promise<Json> {
  const clauses: string[] = ["status = 'confirmed'"];
  const binds: unknown[] = [];
  const date = validDate(args.date);
  const since = validDate(args.since);
  if (date) {
    clauses.push("report_date = ?");
    binds.push(date);
  } else if (since) {
    clauses.push("report_date >= ?");
    binds.push(since);
  }
  if (typeof args.action === "string" && args.action) {
    clauses.push("action = ?");
    binds.push(args.action.toLowerCase());
  }
  if (typeof args.indicator_type === "string" && args.indicator_type) {
    clauses.push("indicator_type = ?");
    binds.push(args.indicator_type.toLowerCase());
  }
  if (typeof args.query === "string" && args.query.trim()) {
    clauses.push("(value LIKE ? OR article_title LIKE ? OR reason LIKE ?)");
    const like = `%${args.query.trim()}%`;
    binds.push(like, like, like);
  }
  const limit = clampLimit(args.limit);
  const { results } = await env.DB.prepare(
    `SELECT * FROM indicators WHERE ${clauses.join(" AND ")}
      ORDER BY report_date DESC, indicator_type, value LIMIT ?`,
  )
    .bind(...binds, limit)
    .all<Json>();
  return {
    count: results.length,
    truncated: results.length >= limit,
    items: results.map((row) => rowToHit(row, caller)),
  };
}

async function lookupMany(env: Env, values: string[], since: string | null, caller: Caller) {
  const wanted = values
    .filter((v) => typeof v === "string" && v.trim())
    .slice(0, MAX_BATCH)
    .map((v) => v.trim());

  const candidateMap = new Map<string, string[]>();
  const allCandidates = new Set<string>();
  for (const value of wanted) {
    // A hash or CVE is matched as given; only hosts expand upward. The
    // expansion walks ~10,300 suffix rules, so it is computed inside the branch
    // that uses it -- a batch of 100 hashes previously paid for 100 walks and
    // discarded every one, on a Worker billed per request.
    const list = /^[0-9a-f]{32,64}$/i.test(value) || /^cve-/i.test(value)
      ? [value.toLowerCase()]
      : hostCandidates(value);
    candidateMap.set(value, list);
    list.forEach((c) => allCandidates.add(c));
  }
  if (allCandidates.size === 0) return [];

  // D1 allows 100 bound parameters per query, and one hostname expands to a
  // candidate per label, so 40 FQDNs already overrun a single statement.
  const PARAMS_PER_QUERY = 90;
  const byValue = new Map<string, Json[]>();
  const candidates = [...allCandidates];
  for (let start = 0; start < candidates.length; start += PARAMS_PER_QUERY) {
    const chunk = candidates.slice(start, start + PARAMS_PER_QUERY);
    const placeholders = chunk.map(() => "?").join(",");
    const binds: unknown[] = [...chunk];
    // value_lc is indexed; wrapping the column in LOWER() would force a scan.
    let sql = `SELECT * FROM indicators WHERE value_lc IN (${placeholders})`;
    if (since) {
      sql += " AND report_date >= ?";
      binds.push(since);
    }
    sql += " ORDER BY report_date DESC";
    const { results } = await env.DB.prepare(sql).bind(...binds).all<Json>();
    for (const row of results) {
      const key = String(row.value).toLowerCase();
      if (!byValue.has(key)) byValue.set(key, []);
      byValue.get(key)!.push(row);
    }
  }

  return wanted.map((value) => {
    const candidates = candidateMap.get(value) ?? [];
    const hits: Json[] = [];
    let matchedOn: string | null = null;
    for (const candidate of candidates) {
      const rows = byValue.get(candidate);
      if (rows && rows.length) {
        matchedOn = candidate;
        hits.push(...rows.map((row) => rowToHit(row, caller)));
        break; // the most specific match wins
      }
    }
    const dates = [...new Set(hits.map((h) => String(h.report_date)))].sort();
    return {
      value,
      found: hits.length > 0,
      matched_on: matchedOn,
      exact: matchedOn !== null && matchedOn === value.toLowerCase(),
      first_seen: dates[0] ?? null,
      last_seen: dates[dates.length - 1] ?? null,
      seen_on: dates,
      hits,
    };
  });
}

/* ------------------------------------------------------------ dispatch --- */

async function callTool(name: string, args: Json, env: Env, caller: Caller): Promise<Json> {
  switch (name) {
    case "list_reports":
      return listReports(env, args);
    case "get_report_summary":
      return reportSummary(env, args);
    case "search_confirmed_iocs":
      return searchIocs(env, args, caller);
    case "lookup_ioc": {
      const value = typeof args.value === "string" ? args.value : "";
      if (!value) return { error: "value is required" };
      const [only] = await lookupMany(env, [value], validDate(args.since), caller);
      return only ?? { value, found: false, hits: [] };
    }
    case "lookup_iocs": {
      const values = Array.isArray(args.values) ? (args.values as string[]) : [];
      if (!values.length) return { error: "values must be a non-empty array" };
      const items = await lookupMany(env, values, validDate(args.since), caller);
      return {
        requested: values.length,
        examined: items.length,
        found: items.filter((i) => i.found).length,
        items,
      };
    }
    default:
      return { error: `unknown tool: ${name}` };
  }
}

function rpcResult(id: unknown, result: unknown): Response {
  return Response.json({ jsonrpc: "2.0", id, result });
}

function rpcError(id: unknown, code: number, message: string, status = 200): Response {
  return Response.json({ jsonrpc: "2.0", id, error: { code, message } }, { status });
}

/* --------------------------------------------------------- heartbeat ----- */

/**
 * Ask D1 whether today's report arrived, and mail if it did not.
 *
 * Runs on a cron trigger rather than on the collecting host: a host that is off
 * or cut off cannot report that it is off. See heartbeat.ts for why this reads
 * the corpus instead of accepting a ping.
 *
 * Never throws. A scheduled handler that throws is retried and logged, and
 * neither does anything useful here -- the operator learns nothing from a
 * retried cron, and an exception loop would bury the one message that matters.
 */
async function readHeartbeatState(env: Env): Promise<HeartbeatState> {
  const row = await env.DB.prepare(
    `SELECT MAX(report_date) AS newest, COUNT(*) AS total FROM reports`,
  ).first<{ newest: string | null; total: number }>();
  return { newest: row?.newest ?? null, totalDays: Number(row?.total ?? 0) };
}

/** Never throws; the caller gets a description either way. */
async function sendAlertMail(env: Env, mail: { subject: string; body: string }): Promise<string> {
  if (!env.RESEND_API_KEY || !env.RESEND_FROM || !env.ALERT_TO) {
    // Loud, because in this state the alarm is armed and mute.
    return "not sent: RESEND_API_KEY, RESEND_FROM or ALERT_TO is unset on the Worker";
  }
  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.RESEND_API_KEY}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        from: env.RESEND_FROM,
        // ALERT_TO, never the report recipients: operational noise must not
        // reach the people who receive the daily report.
        to: env.ALERT_TO.split(",").map((address) => address.trim()).filter(Boolean),
        subject: mail.subject,
        text: mail.body,
      }),
    });
    if (!response.ok) {
      return `not sent: Resend returned ${response.status}: ${(await response.text()).slice(0, 300)}`;
    }
    return "sent";
  } catch (error) {
    return `not sent: ${String(error)}`;
  }
}

async function runHeartbeat(env: Env): Promise<void> {
  let state: HeartbeatState;
  try {
    state = await readHeartbeatState(env);
  } catch (error) {
    // D1 unreachable is its own outage, and the corpus may be perfectly fine.
    // Log it; do not mail a stall that has not been shown to exist.
    console.error(`heartbeat: could not read D1: ${String(error)}`);
    return;
  }

  const today = taipeiDate(new Date());
  const verdict = assess(state, today);
  console.log(
    `heartbeat: newest=${state.newest ?? "none"} today=${today} ` +
      `behind=${verdict.daysBehind} stale=${verdict.stale}`,
  );
  const mail = renderHeartbeat(verdict, state, today);
  if (!mail) return;

  const outcome = await sendAlertMail(env, mail);
  const line = `heartbeat: ${mail.subject} -- ${outcome}`;
  if (outcome === "sent") console.log(line);
  else console.error(line);
}

/**
 * GET reports the verdict and sends nothing. POST sends a test mail, labelled as
 * one, whatever the verdict says -- the point is to prove the mail path on a day
 * when the corpus is healthy, which is every day the alarm is not needed.
 */
async function handleHeartbeatProbe(request: Request, env: Env, caller: Caller): Promise<Response> {
  let state: HeartbeatState;
  try {
    state = await readHeartbeatState(env);
  } catch (error) {
    return Response.json({ error: `could not read D1: ${String(error)}` }, { status: 502 });
  }
  const today = taipeiDate(new Date());
  const verdict = assess(state, today);
  const mail = renderHeartbeat(verdict, state, today);
  const body: Json = {
    today_taipei: today,
    newest_report: state.newest,
    corpus_days: state.totalDays,
    days_behind: verdict.daysBehind,
    stale: verdict.stale,
    reason: verdict.reason,
    // Whether the alarm can speak, without disclosing what it was told.
    alerting_configured: Boolean(env.RESEND_API_KEY && env.RESEND_FROM && env.ALERT_TO),
    would_send: mail ? mail.subject : null,
  };

  if (request.method === "GET") return Response.json(body);
  if (request.method !== "POST") {
    return new Response("method not allowed", { status: 405, headers: { allow: "GET, POST" } });
  }

  const outcome = await sendAlertMail(env, {
    subject: "[threat-pulse] heartbeat test, no action needed",
    body: [
      `This is a test of the heartbeat alarm, sent on request by ${caller.label}.`,
      "Nothing is wrong. It exists so the mail path can be proved on a healthy day,",
      "because the real alarm fires only when the collector has already stopped --",
      "which would otherwise make the day it is most needed the first time it ran.",
      "",
      `Corpus right now: newest report ${state.newest ?? "none"}, ${state.totalDays} days held.`,
      `Today in Taipei is ${today}; the alarm reads that as ${verdict.reason}.`,
      "",
      mail
        ? `A real alert would be sent now, with the subject: ${mail.subject}`
        : "No real alert is due.",
    ].join("\n"),
  });
  body.test_send = outcome;
  console.log(`heartbeat: test send by ${caller.label} -- ${outcome}`);
  return Response.json(body, { status: outcome === "sent" ? 200 : 502 });
}

export default {
  async scheduled(_event: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(runHeartbeat(env));
  },

  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ ok: true, server: "iocs" });
    }

    // An alarm that has never fired is an alarm nobody knows works, and this one
    // fires only when the collector has already stopped -- so it would first be
    // exercised on the day it is most needed. GET reports what the cron would
    // decide right now and sends nothing; POST sends a labelled test so the mail
    // path itself can be proved on a healthy day.
    //
    // The recipient is ALERT_TO, read from the Worker's own secrets. A caller
    // cannot name one, so a leaked token cannot turn this into a way to mail
    // anyone but the operator.
    if (url.pathname === "/heartbeat") {
      const caller = await authenticate(request, env);
      if (!caller) {
        return new Response("unauthorized", {
          status: 401,
          headers: { "www-authenticate": 'Bearer realm="iocs"' },
        });
      }
      return handleHeartbeatProbe(request, env, caller);
    }

    if (url.pathname !== "/mcp") {
      return new Response("not found", { status: 404 });
    }
    if (request.method !== "POST") {
      return new Response("method not allowed", { status: 405, headers: { allow: "POST" } });
    }

    const caller = await authenticate(request, env);
    if (!caller) {
      return Response.json(
        { error: "unauthorized" },
        { status: 401, headers: { "www-authenticate": "Bearer" } },
      );
    }

    let body: Json;
    try {
      body = (await request.json()) as Json;
    } catch {
      return rpcError(null, -32700, "parse error");
    }
    const id = body.id ?? null;
    const method = String(body.method ?? "");
    const params = (body.params ?? {}) as Json;

    switch (method) {
      case "initialize":
        return rpcResult(id, {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: { tools: {} },
          serverInfo: { name: "iocs", version: "1.0.0" },
          instructions:
            "Confirmed IoCs from daily SOC reports, with the action and reason this " +
            "project derived and the source article for each. Read-only; no live " +
            "scraping. Use lookup_iocs for the values pulled out of a log.",
        });
      case "notifications/initialized":
        return new Response(null, { status: 202 });
      case "tools/list":
        return rpcResult(id, { tools: TOOLS });
      case "tools/call": {
        const name = String((params.name as string) ?? "");
        const args = (params.arguments ?? {}) as Json;
        try {
          const result = await callTool(name, args, env, caller);
          return rpcResult(id, {
            content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
            isError: Boolean((result as Json).error),
          });
        } catch (error) {
          return rpcResult(id, {
            content: [{ type: "text", text: `tool ${name} failed: ${String(error)}` }],
            isError: true,
          });
        }
      }
      default:
        return rpcError(id, -32601, `method not found: ${method}`);
    }
  },
};
