/**
 * MCP server for the SOC IoC corpus, served from Cloudflare Workers over D1.
 *
 * The daily job pushes confirmed indicators here; this Worker only reads them.
 * It never scrapes and never returns article bodies - those stay in the audit
 * JSON, because they are 26 publishers' text and no query needs them. Its only
 * writes are per-token usage counters, which hold no submitted value.
 */

import pslRules from "./psl.json";
import { assess, renderHeartbeat, taipeiDate, type HeartbeatState } from "./heartbeat";
import { classifySearchText, MAX_BATCH, partition, type Skipped } from "./guard";
import { lookupAccepted, statusOf, type LookupError } from "./lookup";
import {
  enrichObservables,
  OBSERVABLE_TYPES,
  type CorpusInfo,
  type CveRow,
  type EnrichStore,
  type ExcludedRow,
  type IndicatorRow,
} from "./enrich";
import enrichInputSchema from "./schemas/enrich_observables.input.json";
import enrichOutputSchema from "./schemas/enrich_observables.output.json";
import {
  checkQuota,
  limitsFor,
  renderUsageAlert,
  USAGE_RETENTION_DAYS,
  type QuotaDecision,
  type QuotaLimits,
  type QuotaStore,
} from "./quota";

export interface Env {
  DB: D1Database;
  /** Fallback single token, for a deployment that has not issued any yet. */
  BOOTSTRAP_TOKEN?: string;
  /* Set with `wrangler secret put`. Absent, the heartbeat logs and sends nothing. */
  RESEND_API_KEY?: string;
  RESEND_FROM?: string;
  /** Operational alerts only; never the daily report's recipients. */
  ALERT_TO?: string;
}

// Generated by `npm run psl` from the same list the Python package bundles, so
// the boundary a report was written against matches the one a query uses.
const PSL_NORMAL = new Set(pslRules.normal);
const PSL_WILDCARD = new Set(pslRules.wildcard);
const PSL_EXCEPTION = new Set(pslRules.exception);

const PROTOCOL_VERSION = "2025-06-18";
const MAX_LIMIT = 200;
const DEFAULT_LIMIT = 40;
/**
 * Wall-clock budget for one lookup call. D1 caps a single query at 30 s; this caps
 * the whole call well below that, so a slow database produces an explicit partial
 * response the caller can act on instead of a hung request. It is checked before
 * each D1 query, so a call can overrun it by at most one query.
 */
const LOOKUP_BUDGET_MS = 10_000;
/** Largest JSON-RPC body accepted. A full batch at the per-value length cap fits several times over. */
const MAX_BODY_BYTES = 256 * 1024;

type Json = Record<string, unknown>;

interface Caller {
  label: string;
  scopes: Set<string>;
  /** Key for the usage counters; the stored hash, never the token. */
  quotaKey: string;
  limits: QuotaLimits;
}

/** Implementation-defined JSON-RPC server errors (-32000 to -32099). */
const RATE_LIMITED = -32029;
const QUOTA_UNAVAILABLE = -32030;

/* -------------------------------------------------------------- auth ----- */

async function sha256Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** Constant-time compare, so a wrong token cannot be found byte by byte. */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function authenticate(request: Request, env: Env): Promise<Caller | null> {
  const header = request.headers.get("authorization") ?? "";
  if (!header.startsWith("Bearer ")) return null;
  const presented = header.slice(7).trim();
  if (!presented) return null;

  const hash = await sha256Hex(presented);
  const row = await env.DB.prepare(
    `SELECT label, scopes, expires_at, revoked_at, rate_per_minute, rate_per_day
       FROM tokens WHERE token_sha256 = ?`,
  )
    .bind(hash)
    .first<{
      label: string;
      scopes: string;
      expires_at: string | null;
      revoked_at: string | null;
      rate_per_minute: number | null;
      rate_per_day: number | null;
    }>();

  if (row) {
    if (row.revoked_at) return null;
    if (row.expires_at && new Date(row.expires_at) < new Date()) return null;
    // Usage is recorded so an unused or runaway token is visible later.
    await env.DB.prepare(
      `UPDATE tokens SET last_used_at = ?, call_count = call_count + 1
         WHERE token_sha256 = ?`,
    )
      .bind(new Date().toISOString(), hash)
      .run();
    return {
      label: row.label,
      scopes: new Set(row.scopes.split(/[,\s]+/).filter(Boolean)),
      quotaKey: hash,
      limits: limitsFor(row),
    };
  }

  if (env.BOOTSTRAP_TOKEN && timingSafeEqual(presented, env.BOOTSTRAP_TOKEN)) {
    return { label: "bootstrap", scopes: new Set(["read", "context"]), quotaKey: "bootstrap", limits: limitsFor({}) };
  }
  return null;
}

/* ------------------------------------------------------------ quotas ----- */

function quotaStore(env: Env, key: string): QuotaStore {
  return {
    async take(bucket, limit) {
      // One statement: the row is created at 1, or incremented only while below the
      // limit. When the WHERE fails nothing is updated and nothing is returned.
      const row = await env.DB.prepare(
        `INSERT INTO token_usage (token_sha256, bucket, count) VALUES (?, ?, 1)
           ON CONFLICT (token_sha256, bucket) DO UPDATE SET count = count + 1
           WHERE count < ?
         RETURNING count`,
      )
        .bind(key, bucket, limit)
        .first<{ count: number }>();
      return row !== null;
    },
    async reject(dayBucket) {
      await env.DB.prepare(
        `INSERT INTO token_usage (token_sha256, bucket, count, rejected) VALUES (?, ?, 0, 1)
           ON CONFLICT (token_sha256, bucket) DO UPDATE SET rejected = rejected + 1`,
      )
        .bind(key, dayBucket)
        .run();
    },
  };
}

/**
 * Count one call against the caller's quotas. Null means go ahead; otherwise the
 * response to send instead. `id` is the JSON-RPC id, or undefined for a non-RPC path.
 *
 * A quota that cannot be checked refuses the call rather than waving it through:
 * the database it needs is the one every lookup needs too.
 */
async function enforceQuota(env: Env, caller: Caller, id?: unknown): Promise<Response | null> {
  let decision: QuotaDecision;
  try {
    decision = await checkQuota(quotaStore(env, caller.quotaKey), caller.limits, new Date());
  } catch {
    return refusal(id, 503, QUOTA_UNAVAILABLE, "quota check unavailable; nothing was looked up", {
      reason: "quota_unavailable",
      retry_after_seconds: 30,
    });
  }
  if (decision.allowed) return null;
  return refusal(id, 429, RATE_LIMITED, `rate limit exceeded: ${decision.limit} calls per ${decision.scope}`, {
    reason: "rate_limited",
    scope: decision.scope,
    limit: decision.limit,
    retry_after_seconds: decision.retryAfterSeconds,
  });
}

function refusal(id: unknown, status: number, code: number, message: string, data: Json): Response {
  const headers = { "retry-after": String(data.retry_after_seconds) };
  const body = id === undefined ? { error: data.reason, message, ...data } : { jsonrpc: "2.0", id, error: { code, message, data } };
  return Response.json(body, { status, headers });
}

/* ------------------------------------------------------------- shaping --- */

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

function validDate(value: unknown): string | null {
  return typeof value === "string" && DATE_RE.test(value) ? value : null;
}

function clampLimit(value: unknown): number {
  const n = typeof value === "number" ? Math.floor(value) : DEFAULT_LIMIT;
  return Math.min(Math.max(n, 1), MAX_LIMIT);
}

/**
 * The registry-controlled tail of a host, by the publicsuffix.org algorithm:
 * the rule matching the most labels wins, an exception beats a wildcard, and an
 * unlisted TLD falls back to the implicit `*` rule so a novel TLD does not make
 * the whole host look registrable.
 */
function publicSuffix(labels: string[]): string {
  for (let i = 0; i < labels.length; i += 1) {
    const candidate = labels.slice(i).join(".");
    if (PSL_EXCEPTION.has(candidate)) return labels.slice(i + 1).join(".");
    const parent = labels.slice(i + 1).join(".");
    if (parent && PSL_WILDCARD.has(parent)) return candidate;
    if (PSL_NORMAL.has(candidate)) return candidate;
  }
  return labels[labels.length - 1];
}

/**
 * A log names the host that actually resolved, which is often a child of the
 * host the report named, so `a.b.evil.com` has to still find `evil.com`.
 *
 * Parents stop at the registrable domain. Walking all the way down produced
 * `co.uk` and `github.io` as lookup keys, and a report that named either would
 * then match every unrelated tenant beneath it. Nothing at or above the public
 * suffix belongs to anyone in particular, so nothing there is a useful key.
 */
function hostCandidates(value: string): string[] {
  const host = value.trim().toLowerCase().replace(/\.$/, "");
  if (!host.includes(".") || /^[\d.]+$/.test(host)) return [host];
  const labels = host.split(".");
  const suffixLength = publicSuffix(labels).split(".").length;
  const out: string[] = [];
  for (let i = 0; i <= labels.length - suffixLength - 1; i += 1) {
    out.push(labels.slice(i).join("."));
  }
  // The host is itself a public suffix, so it has no registrable parent. Look
  // it up verbatim rather than returning nothing.
  return out.length ? out : [host];
}

function rowToHit(row: Json, caller: Caller): Json {
  const hit: Json = {
    report_date: row.report_date,
    indicator_type: row.indicator_type,
    value: row.value,
    status: row.status,
    action: row.action,
    priority: row.priority,
    reason: row.reason,
    kev: row.kev === null || row.kev === undefined ? null : Boolean(row.kev),
    kev_due_date: row.kev_due_date,
    cvss_score: row.cvss_score,
    cvss_severity: row.cvss_severity,
    source: row.source,
    article_title: row.article_title,
    article_url: row.article_url,
    section: row.section,
    // Names the rule that kept this off the block list, when one did. The
    // reason string beside it is Chinese prose; a consumer deciding whether a
    // hit is a public resolver or a registry boundary should not have to match
    // substrings of it.
    benign_basis: row.benign_basis ?? null,
    epss_score: row.epss_score ?? null,
    epss_percentile: row.epss_percentile ?? null,
  };
  // The context line is a verbatim source sentence. A token without the scope
  // gets the citation and can read it at the publisher.
  if (caller.scopes.has("context")) hit.context = row.context ?? null;
  return hit;
}

/* --------------------------------------------------------------- tools --- */

const TOOLS = [
  {
    name: "list_reports",
    description: "List ingested daily reports, newest first, with their counts.",
    inputSchema: {
      type: "object",
      properties: { limit: { type: "number", description: "max reports (default 40)" } },
    },
  },
  {
    name: "get_report_summary",
    description:
      "One report's subject, window, priority line and patch/block/hunt/KEV counts. Omit date for the newest.",
    inputSchema: {
      type: "object",
      properties: { date: { type: "string", description: "YYYY-MM-DD" } },
    },
  },
  {
    name: "search_confirmed_iocs",
    description:
      "Search confirmed indicators across every ingested day. Filter by text, action (patch/block/hunt), indicator_type, or a single date. When more rows match than limit (max 200), truncated is true and status is partial; narrow the filters to see the rest. A query that is a private or reserved address, an internal hostname, or a URL with credentials is refused with status skipped rather than searched.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        date: { type: "string", description: "YYYY-MM-DD; omit to search all days" },
        since: { type: "string", description: "YYYY-MM-DD lower bound" },
        action: { type: "string" },
        indicator_type: { type: "string" },
        limit: { type: "number" },
      },
    },
  },
  {
    name: "lookup_ioc",
    description:
      "Look one indicator up across every day. For a hostname it also tries each parent domain, so a log's FQDN still matches a report's apex. A private or reserved address, internal hostname or URL with credentials is returned with status skipped and is never looked up.",
    inputSchema: {
      type: "object",
      properties: {
        value: { type: "string" },
        since: { type: "string", description: "YYYY-MM-DD lower bound" },
      },
      required: ["value"],
    },
  },
  {
    name: "lookup_iocs",
    description:
      "Look up to 100 indicators at once - the values pulled out of a log. Every submitted value comes back exactly once, in items, skipped or errors, with its input_index. Private and reserved addresses, internal hostnames, URLs with credentials and values past the 100th are skipped with a reason and never looked up; a value whose lookup did not complete is an error, never a miss. status is complete, partial or failed; values past the 100th make it partial (truncated is true), and should be resubmitted in another call.",
    inputSchema: {
      type: "object",
      properties: {
        values: { type: "array", items: { type: "string" } },
        since: { type: "string", description: "YYYY-MM-DD lower bound" },
      },
      required: ["values"],
    },
  },
  {
    name: "enrich_observables",
    title: "Enrich observables from published reporting",
    description:
      "Enrich up to 100 observables (CVE, domain, IP, URL, MD5, SHA-1, SHA-256; defanged input accepted) against published vendor and CERT reporting. Every value comes back exactly once, by input_index, in hits, excluded, unseen, skipped or errors. unseen is not a benign verdict. A hit carries the match relation, how many reports and publishers named the value, citations with publication dates, this service's suggested action, and for a CVE the KEV/CVSS/EPSS record with its provenance. corpus_version identifies the corpus; the same version gives the same answer, and it equals the version of an offline bundle built from the same days. status is complete, partial or failed.",
    inputSchema: enrichInputSchema,
    outputSchema: enrichOutputSchema,
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
] as const;

async function listReports(env: Env, args: Json): Promise<Json> {
  const { results } = await env.DB.prepare(
    `SELECT report_date, subject, article_count, confirmed_ioc_count,
            patch_count, block_count, hunt_count, kev_count, unavailable_count,
            generated_at
       FROM reports ORDER BY report_date DESC LIMIT ?`,
  )
    .bind(clampLimit(args.limit))
    .all<Json>();
  return { count: results.length, reports: results };
}

async function reportSummary(env: Env, args: Json): Promise<Json> {
  const date = validDate(args.date);
  const row = date
    ? await env.DB.prepare(`SELECT * FROM reports WHERE report_date = ?`).bind(date).first<Json>()
    : await env.DB.prepare(`SELECT * FROM reports ORDER BY report_date DESC LIMIT 1`).first<Json>();
  if (!row) return { error: date ? `no report for ${date}` : "no reports ingested yet" };
  let enrichment: unknown = null;
  try {
    enrichment = JSON.parse(String(row.enrichment_json ?? "{}"));
  } catch {
    enrichment = null;
  }
  const { enrichment_json, ...rest } = row;
  return { ...rest, enrichment };
}

async function searchIocs(env: Env, args: Json, caller: Caller): Promise<Json> {
  const clauses: string[] = ["status = 'confirmed'"];
  const binds: unknown[] = [];
  const date = validDate(args.date);
  const since = validDate(args.since);
  if (date) {
    clauses.push("report_date = ?");
    binds.push(date);
  } else if (since) {
    clauses.push("report_date >= ?");
    binds.push(since);
  }
  if (typeof args.action === "string" && args.action) {
    clauses.push("action = ?");
    binds.push(args.action.toLowerCase());
  }
  if (typeof args.indicator_type === "string" && args.indicator_type) {
    clauses.push("indicator_type = ?");
    binds.push(args.indicator_type.toLowerCase());
  }
  if (typeof args.query === "string" && args.query.trim()) {
    // A pasted private address or internal name is refused before it reaches a
    // query. Plain words are search terms and pass.
    const refused = classifySearchText(args.query);
    if (refused) return { status: "skipped", reason: refused, count: 0, truncated: false, items: [] };
    clauses.push("(value LIKE ? OR article_title LIKE ? OR reason LIKE ?)");
    const like = `%${args.query.trim()}%`;
    binds.push(like, like, like);
  }
  const limit = clampLimit(args.limit);
  // One row past the limit is fetched so `truncated` says whether rows were left
  // out, rather than only that the limit was reached.
  const { results } = await env.DB.prepare(
    `SELECT * FROM indicators WHERE ${clauses.join(" AND ")}
      ORDER BY report_date DESC, indicator_type, value LIMIT ?`,
  )
    .bind(...binds, limit + 1)
    .all<Json>();
  const truncated = results.length > limit;
  const rows = truncated ? results.slice(0, limit) : results;
  return {
    status: truncated ? "partial" : "complete",
    count: rows.length,
    truncated,
    items: rows.map((row) => rowToHit(row, caller)),
  };
}

interface LookupOutcome {
  status: "complete" | "partial" | "failed";
  truncated: boolean;
  requested: number;
  items: Json[];
  skipped: Skipped[];
  errors: LookupError[];
}

/**
 * Look submitted values up. Skipping happens first, in guard.ts, so a private
 * address or internal hostname never reaches a statement; the rules for what counts
 * as looked up, failed or out of time live in lookup.ts, where they are tested
 * against a fake database. This function only supplies the real one.
 */
async function lookupMany(
  env: Env,
  values: unknown,
  since: string | null,
  caller: Caller,
): Promise<LookupOutcome> {
  const split = partition(values, MAX_BATCH);
  const { items, errors } = await lookupAccepted<Json>(split.accepted, {
    // A hash or CVE is matched as given; only hosts expand upward. The expansion
    // walks ~10,300 suffix rules, so it is computed only where it is used.
    expand: (value) =>
      /^[0-9a-f]{32,64}$/i.test(value) || /^cve-/i.test(value)
        ? [value.toLowerCase()]
        : hostCandidates(value),
    query: async (chunk) => {
      const binds: unknown[] = [...chunk];
      // value_lc is indexed; wrapping the column in LOWER() would force a scan.
      let sql = `SELECT * FROM indicators WHERE value_lc IN (${chunk.map(() => "?").join(",")})`;
      if (since) {
        sql += " AND report_date >= ?";
        binds.push(since);
      }
      sql += " ORDER BY report_date DESC";
      const { results } = await env.DB.prepare(sql).bind(...binds).all<Json>();
      return results;
    },
    keyOf: (row) => String(row.value).toLowerCase(),
    toHit: (row) => rowToHit(row, caller),
    heldBack: (row) => Boolean(row.benign_basis),
    now: () => Date.now(),
    budgetMs: LOOKUP_BUDGET_MS,
    // D1 allows 100 bound parameters per statement, and one hostname expands to a
    // candidate per label, so 40 FQDNs already overrun a single statement. 90 leaves
    // room for the date bound.
    chunkSize: 90,
  });
  return {
    status: statusOf(items.length, errors.length, split.truncated),
    truncated: split.truncated,
    requested: split.requested,
    items,
    skipped: split.skipped,
    errors,
  };
}

/* ------------------------------------------------------------ dispatch --- */

/* ------------------------------------------------------- enrichment --- */

const ENRICH_TYPES = OBSERVABLE_TYPES.map((kind) => `'${kind}'`).join(",");
const INDICATOR_FIELDS = `rowid AS rid, report_date, indicator_type, value, value_lc, action, priority,
  reason, benign_basis, source, article_title, article_url, published_at, context, registrable_lc`;

function enrichStore(env: Env): EnrichStore {
  const placeholders = (n: number) => new Array(n).fill("?").join(",");
  const sinceClause = (since: string | null) => (since ? " AND report_date >= ?" : "");
  const sinceBind = (since: string | null) => (since ? [since] : []);
  return {
    async indicators(keys, since) {
      // The unary + keeps SQLite off the indicator_type index. Without it the
      // planner switches at about sixteen keys and reads every row of those
      // types instead of seeking each value: measured 2026-09-23 on the live
      // database, 9 rows for 8 keys and 4,659 for 16. At the pilot's own quota
      // that is more than the daily row budget of the plan we are on.
      const { results } = await env.DB.prepare(
        `SELECT ${INDICATOR_FIELDS} FROM indicators
          WHERE value_lc IN (${placeholders(keys.length)}) AND +indicator_type IN (${ENRICH_TYPES})${sinceClause(since)}
          ORDER BY report_date, rowid`,
      )
        .bind(...keys, ...sinceBind(since))
        .all<IndicatorRow>();
      return results;
    },
    async children(registrables, since) {
      const { results } = await env.DB.prepare(
        `SELECT ${INDICATOR_FIELDS} FROM indicators
          WHERE registrable_lc IN (${placeholders(registrables.length)}) AND +indicator_type = 'domain'${sinceClause(since)}
          ORDER BY report_date, rowid`,
      )
        .bind(...registrables, ...sinceBind(since))
        .all<IndicatorRow>();
      return results;
    },
    async excluded(keys, since) {
      const { results } = await env.DB.prepare(
        `SELECT report_date, indicator_type, value, value_lc, reason_codes FROM excluded_values
          WHERE value_lc IN (${placeholders(keys.length)})${sinceClause(since)}
          ORDER BY report_date`,
      )
        .bind(...keys, ...sinceBind(since))
        .all<ExcludedRow>();
      return results;
    },
    async cveIntel(ids) {
      const { results } = await env.DB.prepare(
        `SELECT report_date, cve_id, record FROM cve_intel WHERE cve_id IN (${placeholders(ids.length)})`,
      )
        .bind(...ids)
        .all<CveRow>();
      return results;
    },
    async corpus(): Promise<CorpusInfo> {
      const [state, reports] = await env.DB.batch([
        env.DB.prepare(
          `SELECT corpus_version, days, first_date, last_date, publisher_count, psl_version
             FROM corpus_state WHERE id = 1`,
        ),
        env.DB.prepare(`SELECT report_date, report_id, sources_failed FROM reports ORDER BY report_date`),
      ]);
      return {
        state: ((state.results[0] as CorpusInfo["state"]) ?? null),
        reports: reports.results as CorpusInfo["reports"],
      };
    },
  };
}

/** The validator's suffix walk, over the same list the Worker already carries. */
const boundaries = {
  parents(host: string): string[] {
    const labels = host.split(".");
    const depth = publicSuffix(labels).split(".").length;
    const out: string[] = [];
    for (let i = 1; i < labels.length - depth; i += 1) out.push(labels.slice(i).join("."));
    return out;
  },
  registrable(host: string): string {
    const labels = host.split(".");
    const depth = publicSuffix(labels).split(".").length;
    return labels.length > depth ? labels.slice(-(depth + 1)).join(".") : host;
  },
};

async function enrich(env: Env, args: Json, caller: Caller): Promise<Json> {
  if (!Array.isArray(args.values) || !args.values.length) return { error: "values must be a non-empty array" };
  if (args.types !== undefined && (!Array.isArray(args.types) || args.types.length !== args.values.length)) {
    return { error: "types, when given, must be an array the same length as values" };
  }
  if (args.detail !== undefined && args.detail !== "compact" && args.detail !== "full") {
    return { error: "detail must be compact or full" };
  }
  if (args.since !== undefined && validDate(args.since) === null) return { error: "since must be YYYY-MM-DD" };
  return enrichObservables(
    {
      values: args.values,
      types: (args.types as unknown[] | undefined) ?? null,
      detail: args.detail as "compact" | "full" | undefined,
      since: validDate(args.since),
      mayReadContext: caller.scopes.has("context"),
    },
    {
      store: enrichStore(env),
      boundaries,
      now: () => Date.now(),
      requestId: () => crypto.randomUUID(),
      budgetMs: LOOKUP_BUDGET_MS,
      chunkSize: 90,
    },
  );
}

async function callTool(name: string, args: Json, env: Env, caller: Caller): Promise<Json> {
  switch (name) {
    case "list_reports":
      return listReports(env, args);
    case "get_report_summary":
      return reportSummary(env, args);
    case "search_confirmed_iocs":
      return searchIocs(env, args, caller);
    case "lookup_ioc": {
      if (typeof args.value !== "string" || !args.value.trim()) return { error: "value is required" };
      const outcome = await lookupMany(env, [args.value], validDate(args.since), caller);
      // A skipped or failed lookup carries no `found` field at all, so no caller
      // can read it as a miss.
      if (outcome.skipped.length) {
        const { value, reason } = outcome.skipped[0];
        return { status: "skipped", value, reason };
      }
      if (outcome.errors.length) {
        const { value, reason } = outcome.errors[0];
        return { status: "failed", value, reason };
      }
      return { status: "complete", ...outcome.items[0] };
    }
    case "lookup_iocs": {
      if (!Array.isArray(args.values) || !args.values.length) {
        return { error: "values must be a non-empty array" };
      }
      const outcome = await lookupMany(env, args.values, validDate(args.since), caller);
      const found = outcome.items.filter((i) => i.found).length;
      return {
        status: outcome.status,
        truncated: outcome.truncated,
        counts: {
          requested: outcome.requested,
          processed: outcome.items.length,
          skipped: outcome.skipped.length,
          failed: outcome.errors.length,
          found,
        },
        items: outcome.items,
        skipped: outcome.skipped,
        errors: outcome.errors,
        // Kept for callers written against the earlier response shape.
        requested: outcome.requested,
        examined: outcome.items.length,
        found,
      };
    }
    case "enrich_observables":
      return enrich(env, args, caller);
    default:
      return { error: `unknown tool: ${name}` };
  }
}

function rpcResult(id: unknown, result: unknown): Response {
  return Response.json({ jsonrpc: "2.0", id, result });
}

function rpcError(id: unknown, code: number, message: string, status = 200): Response {
  return Response.json({ jsonrpc: "2.0", id, error: { code, message } }, { status });
}

/* --------------------------------------------------------- heartbeat ----- */

/**
 * Ask D1 whether today's report arrived, and mail if it did not.
 *
 * Runs on a cron trigger rather than on the collecting host: a host that is off
 * or cut off cannot report that it is off. See heartbeat.ts for why this reads
 * the corpus instead of accepting a ping.
 *
 * Never throws. A scheduled handler that throws is retried and logged, and
 * neither does anything useful here -- the operator learns nothing from a
 * retried cron, and an exception loop would bury the one message that matters.
 */
async function readHeartbeatState(env: Env): Promise<HeartbeatState> {
  const row = await env.DB.prepare(
    `SELECT MAX(report_date) AS newest, COUNT(*) AS total FROM reports`,
  ).first<{ newest: string | null; total: number }>();
  return { newest: row?.newest ?? null, totalDays: Number(row?.total ?? 0) };
}

/** Never throws; the caller gets a description either way. */
async function sendAlertMail(env: Env, mail: { subject: string; body: string }): Promise<string> {
  if (!env.RESEND_API_KEY || !env.RESEND_FROM || !env.ALERT_TO) {
    // Loud, because in this state the alarm is armed and mute.
    return "not sent: RESEND_API_KEY, RESEND_FROM or ALERT_TO is unset on the Worker";
  }
  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.RESEND_API_KEY}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        from: env.RESEND_FROM,
        // ALERT_TO, never the report recipients: operational noise must not
        // reach the people who receive the daily report.
        to: env.ALERT_TO.split(",").map((address) => address.trim()).filter(Boolean),
        subject: mail.subject,
        text: mail.body,
      }),
    });
    if (!response.ok) {
      return `not sent: Resend returned ${response.status}: ${(await response.text()).slice(0, 300)}`;
    }
    return "sent";
  } catch (error) {
    return `not sent: ${String(error)}`;
  }
}

async function runHeartbeat(env: Env): Promise<void> {
  let state: HeartbeatState;
  try {
    state = await readHeartbeatState(env);
  } catch (error) {
    // D1 unreachable is its own outage, and the corpus may be perfectly fine.
    // Log it; do not mail a stall that has not been shown to exist.
    console.error(`heartbeat: could not read D1: ${String(error)}`);
    return;
  }

  const today = taipeiDate(new Date());
  const verdict = assess(state, today);
  console.log(
    `heartbeat: newest=${state.newest ?? "none"} today=${today} ` +
      `behind=${verdict.daysBehind} stale=${verdict.stale}`,
  );
  const mail = renderHeartbeat(verdict, state, today);
  if (!mail) return;

  const outcome = await sendAlertMail(env, mail);
  const line = `heartbeat: ${mail.subject} -- ${outcome}`;
  if (outcome === "sent") console.log(line);
  else console.error(line);
}

/**
 * Report yesterday's (UTC) client token usage when it crossed a threshold, and drop
 * counters that are no longer needed. Never throws, like the heartbeat. Only token
 * labels and counts are read; the usage table holds nothing else.
 */
async function runUsageCheck(env: Env): Promise<void> {
  const now = new Date();
  const day = new Date(now.getTime() - 86_400_000).toISOString().slice(0, 10);
  try {
    const { results } = await env.DB.prepare(
      `SELECT t.label, t.rate_per_day, u.count, u.rejected
         FROM token_usage u JOIN tokens t ON t.token_sha256 = u.token_sha256
        WHERE u.bucket = ?
        ORDER BY t.label`,
    )
      .bind(`d:${day}`)
      .all<{ label: string; rate_per_day: number | null; count: number; rejected: number }>();
    const usage = results.map((row) => ({
      label: row.label,
      calls: Number(row.count),
      rejected: Number(row.rejected),
      perDay: limitsFor(row).perDay,
    }));
    console.log(
      `usage: day=${day} tokens=${usage.length} calls=${usage.reduce((n, u) => n + u.calls, 0)} ` +
        `rejected=${usage.reduce((n, u) => n + u.rejected, 0)}`,
    );
    const mail = renderUsageAlert(day, usage);
    if (mail) {
      const outcome = await sendAlertMail(env, mail);
      (outcome === "sent" ? console.log : console.error)(`usage: ${mail.subject} -- ${outcome}`);
    }

    const today = now.toISOString().slice(0, 10);
    const oldest = new Date(now.getTime() - USAGE_RETENTION_DAYS * 86_400_000).toISOString().slice(0, 10);
    await env.DB.prepare(
      `DELETE FROM token_usage
        WHERE (bucket LIKE 'm:%' AND bucket < ?) OR (bucket LIKE 'd:%' AND bucket < ?)`,
    )
      .bind(`m:${today}`, `d:${oldest}`)
      .run();
  } catch (error) {
    console.error(`usage: check failed: ${String(error)}`);
  }
}

/**
 * GET reports the verdict and sends nothing. POST sends a test mail, labelled as
 * one, whatever the verdict says -- the point is to prove the mail path on a day
 * when the corpus is healthy, which is every day the alarm is not needed.
 */
async function handleHeartbeatProbe(request: Request, env: Env, caller: Caller): Promise<Response> {
  let state: HeartbeatState;
  try {
    state = await readHeartbeatState(env);
  } catch (error) {
    return Response.json({ error: `could not read D1: ${String(error)}` }, { status: 502 });
  }
  const today = taipeiDate(new Date());
  const verdict = assess(state, today);
  const mail = renderHeartbeat(verdict, state, today);
  const body: Json = {
    today_taipei: today,
    newest_report: state.newest,
    corpus_days: state.totalDays,
    days_behind: verdict.daysBehind,
    stale: verdict.stale,
    reason: verdict.reason,
    // Whether the alarm can speak, without disclosing what it was told.
    alerting_configured: Boolean(env.RESEND_API_KEY && env.RESEND_FROM && env.ALERT_TO),
    would_send: mail ? mail.subject : null,
  };

  if (request.method === "GET") return Response.json(body);
  if (request.method !== "POST") {
    return new Response("method not allowed", { status: 405, headers: { allow: "GET, POST" } });
  }

  const outcome = await sendAlertMail(env, {
    subject: "[threat-pulse] heartbeat test, no action needed",
    body: [
      `This is a test of the heartbeat alarm, sent on request by ${caller.label}.`,
      "Nothing is wrong. It exists so the mail path can be proved on a healthy day,",
      "because the real alarm fires only when the collector has already stopped --",
      "which would otherwise make the day it is most needed the first time it ran.",
      "",
      `Corpus right now: newest report ${state.newest ?? "none"}, ${state.totalDays} days held.`,
      `Today in Taipei is ${today}; the alarm reads that as ${verdict.reason}.`,
      "",
      mail
        ? `A real alert would be sent now, with the subject: ${mail.subject}`
        : "No real alert is due.",
    ].join("\n"),
  });
  body.test_send = outcome;
  console.log(`heartbeat: test send by ${caller.label} -- ${outcome}`);
  return Response.json(body, { status: outcome === "sent" ? 200 : 502 });
}

export default {
  async scheduled(_event: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(runHeartbeat(env));
    ctx.waitUntil(runUsageCheck(env));
  },

  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ ok: true, server: "iocs" });
    }

    // An alarm that has never fired is an alarm nobody knows works, and this one
    // fires only when the collector has already stopped -- so it would first be
    // exercised on the day it is most needed. GET reports what the cron would
    // decide right now and sends nothing; POST sends a labelled test so the mail
    // path itself can be proved on a healthy day.
    //
    // The recipient is ALERT_TO, read from the Worker's own secrets. A caller
    // cannot name one, so a leaked token cannot turn this into a way to mail
    // anyone but the operator.
    if (url.pathname === "/heartbeat") {
      const caller = await authenticate(request, env);
      if (!caller) {
        return new Response("unauthorized", {
          status: 401,
          headers: { "www-authenticate": 'Bearer realm="iocs"' },
        });
      }
      // Counted like a tool call: POST sends mail, and a leaked token should not be
      // able to send it without limit, even to the operator.
      const refused = await enforceQuota(env, caller);
      if (refused) return refused;
      return handleHeartbeatProbe(request, env, caller);
    }

    if (url.pathname !== "/mcp") {
      return new Response("not found", { status: 404 });
    }
    if (request.method !== "POST") {
      return new Response("method not allowed", { status: 405, headers: { allow: "POST" } });
    }

    const caller = await authenticate(request, env);
    if (!caller) {
      return Response.json(
        { error: "unauthorized" },
        { status: 401, headers: { "www-authenticate": "Bearer" } },
      );
    }

    const tooLarge = () =>
      rpcError(null, -32600, `request body exceeds ${MAX_BODY_BYTES} bytes`, 413);
    if (Number(request.headers.get("content-length") ?? "0") > MAX_BODY_BYTES) return tooLarge();
    let body: Json;
    try {
      // Read as text first: the content-length header is optional and can lie.
      const raw = await request.text();
      if (new TextEncoder().encode(raw).length > MAX_BODY_BYTES) return tooLarge();
      body = JSON.parse(raw) as Json;
    } catch {
      return rpcError(null, -32700, "parse error");
    }
    const id = body.id ?? null;
    const method = String(body.method ?? "");
    const params = (body.params ?? {}) as Json;

    // Only tool calls are counted. MCP clients may initialize and list tools before
    // every call, and neither reads the corpus.
    if (method === "tools/call") {
      const refused = await enforceQuota(env, caller, id);
      if (refused) return refused;
    }

    switch (method) {
      case "initialize":
        return rpcResult(id, {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: { tools: {} },
          serverInfo: { name: "iocs", version: "1.0.0" },
          instructions:
            "Confirmed IoCs from daily SOC reports, with the action and reason this " +
            "project derived and the source article for each. Read-only; no live " +
            "scraping. Use lookup_iocs for the values pulled out of a log.",
        });
      case "notifications/initialized":
        return new Response(null, { status: 202 });
      case "tools/list":
        return rpcResult(id, { tools: TOOLS });
      case "tools/call": {
        const name = String((params.name as string) ?? "");
        const args = (params.arguments ?? {}) as Json;
        try {
          const result = await callTool(name, args, env, caller);
          const isError = Boolean((result as Json).error) || (result as Json).status === "failed";
          // Indented only for the small tools a person reads. An enrichment answer
          // can be 400 KiB, and indenting it is CPU spent on whitespace a machine
          // client discards -- which matters on a plan with a 10 ms CPU limit.
          const indent = name === "enrich_observables" ? undefined : 2;
          return rpcResult(id, {
            content: [{ type: "text", text: JSON.stringify(result, null, indent) }],
            // A tool with an output schema returns its result as structured data
            // too, so a caller need not parse the text. An argument error is not a
            // result and carries only the message.
            ...(name === "enrich_observables" && !(result as Json).error ? { structuredContent: result } : {}),
            isError,
          });
        } catch (error) {
          return rpcResult(id, {
            content: [{ type: "text", text: `tool ${name} failed: ${String(error)}` }],
            isError: true,
          });
        }
      }
      default:
        return rpcError(id, -32601, `method not found: ${method}`);
    }
  },
};
